### ISSUE TITLE
[BUG] Failed to install/Package content invalid

### ISSUE THREAD

**Issue by sunsetHue** [Mysterken/DLsiteMetadata#1]
### Bug Description
_Aware this is a WIP fork. Working off install instructions that imply it works._ 

Packing fresh extracted master folder using Playnite 10.33 toolbox and installing throw the following error notification. 

**Notification**
`
Failed to install "DLsiteMetadata_db03c8d9-645a-4359-aafb-01cda945f301_1_0" add-on. Package content invalid.`

**Section from playnite.log**
```
30-05 19:01:27.388|INFO |ExtensionInstaller:Installing extenstion/theme D:\Downloads\DLsiteMetadata_db03c8d9-645a-4359-aafb-01cda945f301_1_0.pext
30-05 19:01:27.480|ERROR|ExtensionInstaller:Failed to install extension D:\Downloads\DLsiteMetadata_db03c8d9-645a-4359-aafb-01cda945f301_1_0.pext
System.Exception: Package content invalid.
   at Playnite.Plugins.ExtensionInstaller.InstallPackedFile[T](String packagePath, String nanifestFileName, String rootDir, Func`2 newMan) in C:\projects\playnite\source\Playnite\Plugins\ExtensionInstaller.cs:line 196
   at Playnite.Plugins.ExtensionInstaller.InstallPackedExtension(String path) in C:\projects\playnite\source\Playnite\Plugins\ExtensionInstaller.cs:line 224
   at Playnite.Plugins.ExtensionInstaller.InstallExtensionQueue() in C:\projects\playnite\source\Playnite\Plugins\ExtensionInstaller.cs:line 137
```

Using the toolbox verify function also throws an error indicating an issue with the manifest. All files are untouched except for being extracted into a folder resembling the toolbox docs.

**Toolbox verify addon**
```
Toolbox.exe verify addon E:\DLsiteMetadata_db03c8d9-645a-4359-aafb-01cda945f301_1_0.pext
Verifying addon manifest E:\DLsiteMetadata_db03c8d9-645a-4359-aafb-01cda945f301_1_0.pext ...
Failed to parse addon manifest YAML:
(Line: 1, Col: 6, Idx: 5) - (Line: 1, Col: 7, Idx: 6): While scanning for the next token, find character that cannot start any token.
```

**Comment by Mysterken** [comment]
All right, had a lot of trouble with that one but it seems a faulty package install on my end prevented me from packing using the Toolbox.

Fixing this by re-cloning my own repo and re-installing the packages seems to have done the trick.

I also[ downgraded Anglesharp to 0.9.9](https://github.com/Mysterken/DLsiteMetadata/commit/2e68ed0252d712ff25676c7428c7108e3fec09e3) to match the current [playnite's version](https://github.com/JosefNemec/Playnite/blob/master/source/Playnite/packages.config) as it is could have [caused the issue](https://api.playnite.link/docs/tutorials/extensions/plugins.html#plugin-dependencies).

I have now a working `.pext` that i'm going to upload as release.

**Comment by Mysterken** [comment]
I have uploaded the first release, let me know if you run into any issues !

https://github.com/Mysterken/DLsiteMetadata/releases/tag/latest

**Comment by sunsetHue** [comment]
It works without any noticeable errors now. **Appreciate the support and your work maintaining this extension.**
